---
- name: Ensure the target directory exists
  ansible.windows.win_file:
    path: C:\ludus\tmechen
    state: directory

- name: Download .NET Installer
  ansible.builtin.include_tasks:
    file: download_file.yml
  vars:
    ludus_download_file_name: dotnet-runtime-6.0.36-win-x64.exe
    ludus_download_file_url: https://builds.dotnet.microsoft.com/dotnet/Runtime/6.0.36/dotnet-runtime-6.0.36-win-x64.exe
    ludus_download_file_host_path: "C:\\ludus\\tmechen"

- name: Install .NET 6.0.36 Runtime
  ansible.windows.win_command: 
    cmd.exe /c C:\ludus\tmechen\dotnet-runtime-6.0.36-win-x64.exe /quiet /norestart
  args:
    creates: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.36

- name: Verify .NET installation
  ansible.windows.win_command: "C:\\Program Files\\dotnet\\dotnet.exe --list-runtimes"
  register: dotnet_version
  changed_when: false

- name: Display installed .NET runtimes
  ansible.builtin.debug:
    msg: "{{ dotnet_version.stdout_lines }}"

- name: Download Zimmermann Tools Installer Archive
  ansible.builtin.include_tasks:
    file: download_file.yml
  vars:
    ludus_download_file_name: Get-ZimmermanTools.zip
    ludus_download_file_url: https://download.ericzimmermanstools.com/Get-ZimmermanTools.zip
    ludus_download_file_host_path: "C:\\ludus\\tmechen"

- name: Unzip Zimmerman Tools
  community.windows.win_unzip:
    src: C:\ludus\Get-ZimmermanTools.zip
    dest: C:\ludus
    remote_src: yes

- name: Ensure the target directory exists
  ansible.windows.win_file:
    path: C:\Tools\EricZimmermann
    state: directory

- name: Execute Zimmerman Tools PowerShell script
  ansible.windows.win_shell: |
    powershell.exe -ExecutionPolicy Bypass -File C:\ludus\Get-ZimmermanTools.ps1 -Dest C:\Tools\EricZimmermann
  args:
    executable: powershell.exe

- name: Create a shortcut for EricZimmermann folder
  community.windows.win_shortcut:
    src: C:\Tools\EricZimmermann\net6
    dest: C:\Users\localuser\Desktop\Tools\Forensic\EricZimmermann.lnk
